import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Artist",
  description: "Generated by create next app",
};

async function getTheme() {
  const res = await fetch("", { cache: "no-store" }); // Replace with your API
  if (!res.ok) throw new Error("Failed to fetch theme");
  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const theme = await getTheme();
  return (
    <html lang="en">
      <head>
      {/* <style>
          {`
            :root {
              
              --primary-color: ${theme.primaryColor};
             
            }
          `}
        </style> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
